// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aajzuzypeuszwnopftjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhanp1enlwZXVzendub3BmdGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDg5NTgsImV4cCI6MjA2NDY4NDk1OH0.AssEpvTLPR8JjsxbRyFpeCpGerlAZeSo1xbgBFMasSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);